### ISSUE TITLE
Repo Links

### ISSUE THREAD

**Issue by buddy-codes** [datkat21/pluto-web-os#4]
There is a link on this repo that redirects to a Replit repl which is old, and it should redirect to [pluto](https://datkat21.github.io/pluto-web-os/)

**Comment by buddy-codes** [comment]
not redirect, the link should be pluto

**Comment by datkat21** [comment]
Fixed.
![image](https://github.com/datkat21/pluto-web-os/assets/49850194/f0bed537-a8f7-4f03-8f7d-1d82609c7c43)
